### ISSUE TITLE
issue-5-search-entries

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/code-journal#9]
## 💰 Motivation

Coders will want to search through their entries and display entries that match a keyword

## 📐 Plan

Create a responsive search field that will display entires that match the provided keyword

## 🖼️ Wireframes

![image](https://github.com/kepsteen/code-journal/assets/118944207/a3658f49-823f-4166-9e43-6ff57bb02353)

## ✅ Task List
- [x] Add an input element to the header in your HTML
  - [x] Add magnifying glass placeholder in input field
- [x] Add event listener to input on the search bar element
- [x] write a callback function that does the following
  - [x] searches through the data.entries title and notes to find any entries that match the keyword
  - [x] render only the entries that match the keyword
  - [x] When the input field is blank render all the entries 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
